backend:
  name: git-gateway
  branch: master # main atau master

media_folder: "public/uploads" # Lokasi di Git
public_folder: "/uploads" # Path URL di situs

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}

      - {label: "Description", name: "description", widget: "string", required: false}

      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: true}

      - {label: "Scheduled Date", name: "scheduled", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false}

      # Bidang 'layout' (biasanya tidak perlu diubah melalui CMS, tapi bisa ditambahkan)
      # Jika Anda ingin pengguna bisa memilih layout, Anda bisa pakai widget 'select' atau 'hidden'
      # - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"} # Contoh hidden field

      - {label: "Is Draft?", name: "draft", widget: "boolean", default: true}

      - {label: "Body", name: "body", widget: "markdown"}